### ISSUE TITLE
Remove PrivateMap

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-abstract-refs#11]
Since "clear" was removed from WeakMap, we no longer have strong motivation for PrivateMap.

**Comment by uMaxmaxmaximus** [comment]
[My solution](https://github.com/tc39/proposal-private-fields/issues/36): Yes, these properties can be obtained through Object.getOwnPropertySymbols.

BUUUT!! Private property is not protected against hackers !! It's only an abstraction, which allows to avoid conflicts NAMES !!

In addition, we may well make  2 functions:
1) Object.getOwnPropertySymbols() return symbols that have been set in current file
2) Object.getOwnPropertySymbolsAll() return symbols that have been set in ALL files

**Comment by HyeonuPark** [comment]
No idea about the meaning of "dry/wet membrane". Can someone explain it please?
And also, should `Proxy<Symbol>` treated as a `Symbol`? I thought it's just a plain Proxy object that targets Symbol.

**Comment by spion** [comment]
If I understand correctly, the simplified explanation is as follows:

Even if we added `{hidden: true}` to `Object.defineProperty` which ensures that there is no way to get the property symbol (through `Object.getOwnPropertySymbols(o)`), there is still the Proxy problem:

Basically, when you do `this[privateSymbol]` or `otherObject[privateSymbol]`, you are announcing that privateSymbol to the object (`this` / `otherObject`)

Both of these can be intercepted by a proxy that wraps the original object and traps all property lookups to that object. The first time a method is invoked that tries to access the `privateSymbol` property, this symbol will be passed to [the `get` proxy handler](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/get). After that, the code that created the proxy has access to the symbol and therefore direct access to the private properties of the original object.

**Comment by erights** [comment]
Hi @spion yes, that is an accurate summary of the most important issue. By itself one could imagine "fixing" this problem with a more complex API, which an earlier proposal actually tried to do. But that got really complicated and left other fundamental problems unsolved.

Rather that re-explain here what those remaining problems are, once wiki.ecmascript.org is back online (attn @dherman ) I can point you at some useful explanations.
