### ISSUE TITLE
Comparison with my proposal

### ISSUE THREAD

**Issue by dead-claudia** [zenparsing/es-abstract-refs#13]
I came up with this independently (I was driven by completely different concerns), but I have a very similar proposal here: https://github.com/isiahmeadows/private-data-proposal

The main difference I see between this and mine are that:

1. I restrict the slots to allocation time - they can't be added at any other point. (This is for performance - engines can lower it to just an offset.)
1. I scope them to where the object is allocated, and since I don't have facilities for object literals inheriting slots from other objects, I don't have facilities for things like private interface slots or anything like that, since objects have no equivalent to `extends`.

There's probably a few others I missed, but I just wanted your thoughts.

*([This](https://github.com/tc39/proposal-class-fields/issues/106#issuecomment-403142380) prompted me to ask about it here.)*

**Comment by zenparsing** [comment]
Hi @isiahmeadows .

The big difference here is that this proposal (leaving aside the "possible private syntax" thing at the bottom of the README) introduces no syntax **hiding** the WeakMap behind some lexically scoped `private` name abstraction.

I now believe that the parallel lexical namespace used for private names does not hold it's weight: it causes many more problems than it solves. I also believe that any syntax that hides the WeakMap does more harm than good.

I've created a new repo at https://github.com/zenparsing/proposal-abstract-references which eliminates all references to "PrivateMap" and the `private` keyword thing.

**Comment by dead-claudia** [comment]
Okay. I'll go ahead and close this, then.
