### ISSUE TITLE
As is, WeakMaps don't implement private fields

### ISSUE THREAD

**Issue by claudepache** [zenparsing/es-abstract-refs#6]
The issue is that WeakMaps have a `.clear()` method, which alters (in that case, more precisely, deletes) the values associated to keys without mandating explicit references to the keys. That violates privacy.

Instead of WeakMap, one should use a structure which is tailored for privacy, not for weakness.

**Comment by erights** [comment]
Just recording for the record that the .clear method was withdrawn from WeakMaps before standardization, precisely because of its unfriendliness to issues such as this.

**Comment by claudepache** [comment]
> Just recording for the record that the .clear method was withdrawn from WeakMaps before standardization, precisely because of its unfriendliness to issues such as this.

Yes, except that the spec text still does not suggest that privacy is a desired property of WeakMap (and WeakSet); currently it seems to just be a side-effect of the limitation of the API.
