### ISSUE TITLE
Should private map traverse prototypes?

### ISSUE THREAD

**Issue by zenparsing** [zenparsing/es-abstract-refs#8]
Currently, `referenceGet` on Map-types will traverse the target's prototype chain, mirroring standard property lookup behavior.  Is this desirable?

When accessing the internal slots of JS standard library objects, we don't traverse prototypes.  For example:

```
>> var d = new Date;
>> var dd = Object.create(d);
>> d.getTime()
1415510438712
>> dd.getTime()
TypeError: this is not a Date object.
```

I think the "no-share" model for private state might make more sense.  

Let's say we have an object P which is trademarked using a private field TM.  If objects inherited the private state of their prototype parents, then arbitrary objects could be created which exhibit TM by simply using `Object.create(P)`.

**Comment by erights** [comment]
Sorry for the extremely delayed response. Yes, removing prototype traversal was the right step.
