### ISSUE TITLE
Actually bind the function

### ISSUE THREAD

**Issue by ForbesLindesay** [zenparsing/es-abstract-refs#9]
Shouldn't it be:

``` js
Function.prototype[Symbol.referenceGet] = function(base) { return this.bind(base); };
```

rather than:

``` js
Function.prototype[Symbol.referenceGet] = function(base) { return this };
```

The goal being that:

``` js
var a = {
  foo: function () {
    assert(this === a);
  }
};

var foo = a::foo;

foo();
```

works.  Without the binding, the assertion doesn't pass.

**Comment by zenparsing** [comment]
@ForbesLindesay You may have seen this already, but the two new proposals are at:
- https://github.com/zenparsing/es-function-bind
- https://github.com/zenparsing/es-private-fields
